language: java
jdk:
 - openjdk7
script:
 - mvn install -DskipTests=false
 #- git commit -a -m "commit do travis para github"
 - git log origin/master.. --stat
 - git config --global user.email "masterprojectrn@yahoo.com.br"
 - git config --global user.name "masterprojectrn"
 - git config --global user.password "gibeongerencia1"
 - git tag -a T$TRAVIS_JOB_ID -m "criando tag"
 - git push https://masterprojctrn:gibeongerencia1@github.com/gerencia-configuracao-mudanca/bancogcm.git master

deploy:
  provider: heroku
  api_key: "4e82f042-5b89-4f7c-bc8e-a226ff524236"
